name: Gallery
markdown: redcarpet
pygments: true
permalink: /:year/:month/:title/
url: http://fdanangp.github.io/gallery/
author:
    name: Firdani Danang Prakoso
    twitter: #
# SITE CONFIGURATION
baseurl: "/gallery" # the subpath of your site, e.g. /blog/
url: "http://fdanangp.github.io" # the base hostname & protocol for your site
